name: Build and Upload Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "$HOME/.arduino15/bin" >> $GITHUB_PATH
          arduino-cli version

      - name: Install ESP32 core
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Compile firmware
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32s3 firmware/JcorpNomadProject/JcorpNomadProject.ino

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: firmware/JcorpNomadProject/build/esp32.esp32s3/firmware.bin
