name: Build ESP32-S3 Firmware

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "$PWD/bin" >> $GITHUB_PATH
      
      - name: Verify Arduino CLI version
        run: arduino-cli version

      - name: Install ESP32 Core
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Install required libraries
        run: |
          arduino-cli lib update-index
          arduino-cli lib install ESPAsyncWebServer
          arduino-cli lib install ArduinoJson@7.3.0
          arduino-cli lib install lvgl@8.3.10

      - name: Compile Firmware
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32s3 firmware/JcorpNomadProject/JcorpNomadProject.ino

      - name: Upload Firmware Binary
        uses: actions/upload-artifact@v4
        with:
          name: jcorp-nomad-firmware
          path: firmware/JcorpNomadProject/build/esp32.esp32s3/firmware.bin
